/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mt_mtxx_image_JNI */

#ifndef _Included_com_mt_mtxx_image_JNI
#define _Included_com_mt_mtxx_image_JNI


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    AutoColor
 * Signature: ([BIIII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_AutoColor
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    AutoColorLevel
 * Signature: ([BIIZ)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_AutoColorLevel
  (JNIEnv *, jobject, jbyteArray, jint, jint, jboolean);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    AutoConstrast
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_AutoConstrast
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    AutoWhiteBalance
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_AutoWhiteBalance
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    BackWeak
 * Signature: ([B[BII[I[II[BII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_BackWeak
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jintArray, jintArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    BackWeak2
 * Signature: ([BIIII[BII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_BackWeak2
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    BackWeakLine
 * Signature: ([I[III[I[IFII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_BackWeakLine
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jintArray, jintArray, jfloat, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    BackWeakOne
 * Signature: ([I[IIIII[BII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_BackWeakOne
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    CColorBalance
 * Signature: (ZIIII[BII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_CColorBalance
  (JNIEnv *, jobject, jboolean, jint, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ColorModeEx
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ColorModeEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    CompositeColorEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_CompositeColorEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    DrawEx
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_DrawEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ExclusionEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ExclusionEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ExclusionEx2
 * Signature: ([BBBBD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ExclusionEx2
  (JNIEnv *, jobject, jbyteArray, jbyte, jbyte, jbyte, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    FaceBeauty
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_FaceBeauty
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    FaceBeautyRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_FaceBeautyRelease
  (JNIEnv *, jobject);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    FrameXCBK
 * Signature: ([I[IIII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_FrameXCBK
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    GaussIIRBlurBrush
 * Signature: ([IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_GaussIIRBlurBrush
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    GaussIIRBlurImage
 * Signature: ([BIIII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_GaussIIRBlurImage
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    GetDegreeByPoints
 * Signature: (IIII)D
 */
JNIEXPORT jdouble JNICALL Java_com_mt_mtxx_image_JNI_GetDegreeByPoints
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    Grayscale
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_Grayscale
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    HardlightEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_HardlightEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ImageColorBurnEx
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ImageColorBurnEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ImageDarkenEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ImageDarkenEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ImageExclusionEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ImageExclusionEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ImageLightenEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ImageLightenEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ImageNormalEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ImageNormalEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ImageOverlayEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ImageOverlayEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ImageScreenEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ImageScreenEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ImageSoftLightEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ImageSoftLightEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    LOMO1
 * Signature: ([III[I)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_LOMO1
  (JNIEnv *, jobject, jintArray, jint, jint, jintArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    LOMO2
 * Signature: ([III[I)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_LOMO2
  (JNIEnv *, jobject, jintArray, jint, jint, jintArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    LightEnEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_LightEnEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    MakeAllTransparent
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_MakeAllTransparent
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    MultipleEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_MultipleEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    NoiseEx
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_NoiseEx
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    NormalEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_NormalEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    OldImage
 * Signature: ([BII[BII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_OldImage
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    PinLightEx
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_PinLightEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    PtChangeByRotate
 * Signature: ([BDDD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_PtChangeByRotate
  (JNIEnv *, jobject, jbyteArray, jdouble, jdouble, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    RGBtoXYZ
 * Signature: (BBB[B)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_RGBtoXYZ
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyteArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    RGBtoYIQ
 * Signature: (BBB[B)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_RGBtoYIQ
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyteArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    RGBtoYUV
 * Signature: (BBB[B)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_RGBtoYUV
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyteArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    Resample
 * Signature: ([BIII[BII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_Resample
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    SSkinbeautify
 * Signature: ([IIIIIID)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_SSkinbeautify
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint, jint, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ScreenEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ScreenEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    SetBackWeakRadius
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_SetBackWeakRadius
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    SetColorImage
 * Signature: ([BIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_SetColorImage
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    SetGrayScaleEx
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_SetGrayScaleEx
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    Sharp
 * Signature: ([IIIFF)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_Sharp
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat, jfloat);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    SharpPreview
 * Signature: ([IIIFF)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_SharpPreview
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat, jfloat);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    SharpPreviewRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_SharpPreviewRelease
  (JNIEnv *, jobject);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    ShiftRGBEx
 * Signature: ([BBBB)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_ShiftRGBEx
  (JNIEnv *, jobject, jbyteArray, jbyte, jbyte, jbyte);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    SkinWhite
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_SkinWhite
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    SoftLightEx
 * Signature: ([B[BD)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_SoftLightEx
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleBaoColor
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleBaoColor
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleCinnamon
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleCinnamon
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleClassic
 * Signature: ([IIID)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleClassic
  (JNIEnv *, jobject, jintArray, jint, jint, jdouble);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleClassicStudio
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleClassicStudio
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleEP1
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleEP1
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleEP2
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleEP2
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleElegant
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleElegant
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleElegantNew
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleElegantNew
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleFP1
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleFP1
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleFP2
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleFP2
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleFilm
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleFilm
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleGP1
 * Signature: ([I[III[BI)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleGP1
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleGP2
 * Signature: ([I[III[BI)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleGP2
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleImpression
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleImpression
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleJapanese
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleJapanese
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleLomoAP1
 * Signature: ([I[III[BI)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleLomoAP1
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleLomoAP2
 * Signature: ([I[III[BI)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleLomoAP2
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleLomoB
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleLomoB
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleLomoBrightRed
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleLomoBrightRed
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleLomoC
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleLomoC
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleLomoChristmas
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleLomoChristmas
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleLomoHDR
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleLomoHDR
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleMilk1
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleMilk1
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleMilk2
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleMilk2
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleMilk3
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleMilk3
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleMilk4
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleMilk4
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleOldPhoto
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleOldPhoto
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleOldPhotoP1
 * Signature: ([I[III[BI)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleOldPhotoP1
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleOldPhotoP2
 * Signature: ([I[III[BI)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleOldPhotoP2
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    StyleRetro
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_StyleRetro
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    XYZtoRGB
 * Signature: (BBB[B)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_XYZtoRGB
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyteArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    YIQtoRGB
 * Signature: (BBB[B)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_YIQtoRGB
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyteArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    YUVtoRGB
 * Signature: (BBB[B)V
 */
JNIEXPORT void JNICALL Java_com_mt_mtxx_image_JNI_YUVtoRGB
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyteArray);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    add
 * Signature: (IB)I
 */
JNIEXPORT jint JNICALL Java_com_mt_mtxx_image_JNI_add
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     com_mt_mtxx_image_JNI
 * Method:    deal
 * Signature: ([BIIIILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mt_mtxx_image_JNI_deal
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
